### ISSUE TITLE
Optional fields in json-schema won't create optional field in avro

### ISSUE THREAD

**Issue by sudhirpatil** [thedumbterminal/jsonschema-avro#13]
Optional fields in json-schema won't create optional field in avro

json schema with optional field "gender"
{"type": "object", "properties": {"name": { "type": "string" }, "gender": { "type": "string"}}, "required": ["name"]}

avro schema with no optional field
{"name":"main","type":"record","fields":[{"name":"name","doc":"","type":"string"},{"name":"gender","doc":"","type":"string"}]}

**Comment by thedumbterminal** [comment]
Cheers for this I'll take a look....

**Comment by thedumbterminal** [comment]
Looking at this: https://stackoverflow.com/questions/29299610/is-it-possible-to-have-an-optional-field-in-an-avro-schema-i-e-the-field-does It seems that an optional field can be specified with a type of null, in this case the input json schema schema would need to contain null fields.

Thoughts?

**Comment by sudhirpatil** [comment]
No, not needed in json-schema. In json-schema fields in the "required" field is mandatory, all others are optional. so in given example only name is required field & gender field is optional.
{"type": "object", "properties": {"name": { "type": "string" }, "gender": { "type": "string"}}, **"required": ["name"]**}

Link you shared is for avro (& not json-schema), yes thats the one way to optional field in. Other ways to say optional fields in avro from quick search.
{"name": "next", "type": ["null", "LongList"]} // optional next element
{"name":"x","type":["long","null"],"default":null} 
{"name":"y", "type":["null", "long"], "default": 0}

**Comment by sudhirpatil** [comment]
const jsonSchemaAvro = module.exports = {}

// Json schema on the left, avro on the right
const typeMapping = {
	'string': 'string',
	'null': 'null',
	'boolean': 'boolean',
	'integer': 'int',
	'number': 'float'
}


const reSymbol = /^[A-Za-z_][A-Za-z0-9_]*$/;

jsonSchemaAvro.convert = (jsonSchema) => {
	if(!jsonSchema){
		throw new Error('No schema given')
	}
	return {
		namespace: jsonSchemaAvro._convertId(jsonSchema.id),
		name: 'main',
		type: 'record',
		doc: jsonSchema.description,
		fields: jsonSchema.properties ? jsonSchemaAvro._convertProperties(jsonSchema) : []
	}
}

jsonSchemaAvro._convertId = (id) => {
	return id ? id.replace(/([^a-z0-9]+)/ig, '.') : id
}

jsonSchemaAvro._isComplex = (schema) => {
	return schema.type === 'object'
}

jsonSchemaAvro._isArray = (schema) => {
	return schema.type === 'array'
}

jsonSchemaAvro._hasEnum = (schema) => {
	return Boolean(schema.enum)
}

jsonSchemaAvro._convertProperties = (jsonSchema) => {
    var schema = jsonSchema.properties
    var requiredFields = jsonSchema["required"] || []

	return Object.keys(schema).map((item) => {
		if(jsonSchemaAvro._isComplex(schema[item])){
			return jsonSchemaAvro._convertComplexProperty(item, schema[item])
		}
		else if (jsonSchemaAvro._isArray(schema[item])) {
			return jsonSchemaAvro._convertArrayProperty(item, schema[item], requiredFields)
		}
		else if(jsonSchemaAvro._hasEnum(schema[item])){
			return jsonSchemaAvro._convertEnumProperty(item, schema[item], requiredFields)
		}
		return jsonSchemaAvro._convertProperty(item, schema[item], requiredFields)
	})
}

jsonSchemaAvro._convertComplexProperty = (name, contents) => {
	return {
		name: name,
		doc: contents.description || '',
		type: {
			type: 'record',
			name: `${name}_record`,
			fields: jsonSchemaAvro._convertProperties(contents || {})
		}
	}
}

jsonSchemaAvro._convertArrayProperty = (name, contents, requiredFields) => {
	return {
		name: name,
		doc: contents.description || '',
		type: {
			type: 'array',
			items: jsonSchemaAvro._isComplex(contents.items)
				? {
					type: 'record',
					name: `${name}_record`,
					fields: jsonSchemaAvro._convertProperties(contents.items.properties || {})
				}
				: jsonSchemaAvro._convertProperty(name, contents.items)
		}
	}
}

jsonSchemaAvro._convertEnumProperty = (name, contents, requiredFields) => {
	const valid = contents.enum.every((symbol) => reSymbol.test(symbol))
	let prop = {
		name: name,
		doc: contents.description || '',
		type: valid ? {
			type: 'enum',
			name: `${name}_enum`,
			symbols: contents.enum
		} : 'string'
	}
	if(contents.hasOwnProperty('default')){
		prop.default = contents.default
	}
	return prop
}

jsonSchemaAvro._convertProperty = (name, value, requiredFields) => {
	let prop = {
		name: name,
		doc: value.description || ''
	}
	if(value.hasOwnProperty('default')){
		prop.default = value.default
	}

	var isRequiredField = requiredFields.indexOf(name)
	if(Array.isArray(value.type)){
	    if(isRequiredField >= 0){
	        prop.type = value.type.map(type => typeMapping[type])
	    }else{
		    prop.type = value.type.map(type => ["null", typeMapping[type]])
	    }
	}
	else{
	    if(isRequiredField >= 0){
	        prop.type = typeMapping[value.type]
	    }else{
		    prop.type = ["null", typeMapping[value.type]]
	    }
	}
	return prop
}

**Comment by sudhirpatil** [comment]
pasted code with fix for optional types. Notes not handling optional fields with type array & enum

**Comment by thedumbterminal** [comment]
I've added support for optional properties in master, does anyone want to test before release?

**Comment by thedumbterminal** [comment]
Resolved in version 1.6.0
