### ISSUE TITLE
Complex one is not working 

### ISSUE THREAD

**Issue by venkatrmrddy** [thedumbterminal/jsonschema-avro#8]
I tried with complex Json it failed to convert Avro schema

**Comment by thedumbterminal** [comment]
Hi thanks for raising an issue @venkatrmrddy could you add the problem schema to this issue so I can look into this, thanks.

**Comment by thedumbterminal** [comment]
Any further info on this @venkatrmrddy ?

**Comment by thedumbterminal** [comment]
@venkatrmrddy closing this issue as I've had no further info from you. Feel free to re-open this info when you have an example JSON schema that fails to convert.
